name: Build

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

jobs:
    build-normal:
        name: Build Normal Docker Images (node:16.18.0, playwright:1.30.0)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push Docker Image
              env:
                IMAGE_VERSION: 0.0.1
                NODE_VERSION: 16.18.0
                PLAYWRIGHT_VERSION: 1.30.0
              run: ./scripts/build.sh

            - name: Tag Image Alias
              run: |
                  npm i -g regctl
                  regctl registry login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
                  regctl image copy caspianzhao/playwright:all caspianzhao/playwright:latest
                  regctl registry logout

    build-light:
        name: Build Light Docker Images (node:16.18.0, playwright:1.30.0)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push Docker Image
              env:
                IMAGE_VERSION: 0.0.1
                NODE_VERSION: 16.18.0
                PLAYWRIGHT_VERSION: 1.30.0
              run: ./scripts/build-light.sh

    update-readme:
        name: Update Docker Readme
        runs-on: ubuntu-latest
        needs:
            - build-normal
            - build-light
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Update Readme
              run: node ./scripts/update.js

            - name: Docker Hub Description
              uses: peter-evans/dockerhub-description@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
                  repository: caspianzhao/playwright
